### ISSUE TITLE
Format code chunks/styling

### ISSUE THREAD

**Issue by adamhsparks** [mladencucak/AnalysisPLBIreland#10]
Standardise indents, and whatnot using RStudio's built-in code formatting, _e.g._, highlight code chunk and use `ctrl + shift + a`.

https://csgillespie.github.io/efficientR/coding-style.html

**Comment by mladencucak** [comment]
I use this but sometimes it doesn't work and sometimes it splits code too much, but it is a good place to start. Thanks.
