### ISSUE TITLE
Analysis.Rmd Line 628, `data.Rdata` object name should be more descriptive

### ISSUE THREAD

**Issue by adamhsparks** [mladencucak/AnalysisPLBIreland#3]
The data object saved on Line 628 should not be named "data".

`data()` is a reserved base R function and when the object is imported it comes in as `data`, which clobbers the R function. This is not best practice. We should pick a more descriptive name for this object.

This will involve refactoring several code chunks in "Results1.Rmd" for the new name but will not have any other major side-effects.

**Comment by mladencucak** [comment]
sorted.
