### ISSUE TITLE
Analysis.Rmd, {irish_model} code chunk (and others) are very long

### ISSUE THREAD

**Issue by adamhsparks** [mladencucak/AnalysisPLBIreland#5]
We should strive to have shorter code chunks. 

Looking at two in particular, `{r irish-model}` and `{r sens-spec-calc}`, I realise a whole function like this is hard to shorten, so I'd suggest moving the functions to separate R script files and sourcing them to load/run where needed unless the whole function really needs to be displayed in the compendium, which I don't find necessary, but you may.

Also, it should be better documented as to what the input parameters are and what the expected output is for these functions.

The `{r plotROC}` code chunk should just be broken up or not included in the knitted output.

**Comment by mladencucak** [comment]
Updated some changes to Analysis - Let me know what you think.
That is an interesting question. I agree that it is huge and maybe a bit disturbing. 
 We had a chat about moving functions into a separate script.  For compendium - I believe it should all be there, and if someone wants to reproduce, again having it all at one place is better.  When making a project, it is definitely much better to have things shorter and better organised. I am wondering what will happen now, I am writing a new model... it will be an even a bigger mess. 

Documenting - well that is in paper and reference is there. That was something I was thinking about - how much do you write here? There is paper for that. I don't think the medium is there to describe everything. If I get to the package idea, maybe it should be documented better.

**Comment by adamhsparks** [comment]
Counterpoint. If someone is really interested in the whole function, you have it right there in the repository on GitHub, provide a link to it.

When I say documentation for the function, I mean documenting the R function properly. What are the parameters' inputs and what's the expected returned value. Think about what you get when you browse a help file for an R function.

Not the model itself, I agree, that's in the paper.

**Comment by mladencucak** [comment]
Hmm..so a package? I am not sure I know how to "properly document" the function outside...

**Comment by adamhsparks** [comment]
Not saying you have to make a whole package, but when you search for help it tells you what each parameter setting does. That's based on something like this.

Something very simple at the top like:

```r
#' @param weather a ????? providing yyyy.
#' @param param a ????? doing XXXX. TRUE/FALSE
#' @param infill_gap perform ZZZZ operation. TRUE/FALSE

#' @return A vectordataframeofvalues
```

So something stylised like that to instruct, or at the least in the text itself outside the code chunk describing the parameters of the function. That may be more desirable and can be nicely formatted.

_e.g._

* **weather** A a ????? providing yyyy.
* **param** A ????? doing XXXX. `TRUE`/`FALSE`
* **infill_gap** perform ZZZZ operation. `TRUE`/`FALSE`

**Comment by mladencucak** [comment]
How about this? https://github.com/rstudio/rmarkdown/issues/664 
or this: https://stackoverflow.com/questions/42543431/code-folding-for-individual-chunks-in-r-markdown
Perhaps make it foldable? 
I did not know you can actually do this outside of the package, but it makes sense... Let me look into that. I have already started doing this in the blight package.

**Comment by adamhsparks** [comment]
Nice! I like that if you have time.

**Comment by mladencucak** [comment]
I have folded some of the bigger chunks. 
I have added some descriptions of the functions. Let me know what you think.
