### ISSUE TITLE
Analysis.Rmd, Lines 162, 167, 172 and 177 use `&&`

### ISSUE THREAD

**Issue by adamhsparks** [mladencucak/AnalysisPLBIreland#7]
From reading the code, I think you mean to use only `&`?

See: http://promberger.info/linux/2008/09/12/r-logical-operators-beware-of-the-difference-between-and/

**Comment by mladencucak** [comment]
Don't remember why did I do that. It shouldn't change anything because those are not vectors. Thanks.

**Comment by adamhsparks** [comment]
Shouldn't change anything, no, but not best practice. :)
