### ISSUE TITLE
Use a standard theme and pallet for graphs?

### ISSUE THREAD

**Issue by adamhsparks** [mladencucak/AnalysisPLBIreland#8]
Standardising on a graph theme (which you've mostly done) and a pallet would enhance the aesthetics and make it easier to follow for the reader.

Some are colour, some are black and white. The coloured pallets aren't all the same.

**Comment by mladencucak** [comment]
Yes. Development over time. Could standardise. Good point.

**Comment by adamhsparks** [comment]
For the `ggplot2` graphs, you can use a `theme_set()` command at the head of the file to apply to all of the plots. The colours you'll just have to be conscientious of throughout though.

**Comment by mladencucak** [comment]
mostly sorted
